### ISSUE TITLE
'TrainArgument' object has no attribute 'f_divergence_type'

### ISSUE THREAD

**Issue by ggbondcxl** [mst272/LLM-Dojo#4]
```python
2024-07-27 00:22:19.997 | INFO     | __main__:initial_args:45 - common_args:TrainArgument(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_co
nfigured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
batch_eval_metrics=False,
beta=0.1,
bf16=True,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
dataset_num_proc=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=./train_args/deepspeed_config/ds_config_zero2.json,
disable_dropout=True,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=no,
eval_use_gather_object=False,
evaluation_strategy=no,
force_use_ref_model=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generate_during_eval=False,
gradient_accumulation_steps=16,
gradient_checkpointing=True,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
is_encoder_decoder=None,
jit_mode_eval=False,
label_names=None,
label_pad_token_id=-100,
label_smoothing=0,
label_smoothing_factor=0.0,
learning_rate=0.0002,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=/hdd/u202320081001054/LLM-Dojo/output/runs/Jul27_00-22-19_gpu3,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=100,
logging_strategy=steps,
loss_type=sigmoid,
lr_scheduler_kwargs={},
lr_scheduler_type=constant_with_warmup,
max_grad_norm=1.0,
max_length=8192,
max_prompt_length=4096,
max_steps=-1,
max_target_length=None,
metric_for_best_model=None,
model_adapter_name=None,
model_init_kwargs=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=1,
optim=paged_adamw_32bit,
optim_args=None,
optim_target_modules=None,
output_dir=/hdd/u202320081001054/LLM-Dojo/output,
overwrite_output_dir=False,
padding_value=0,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=2,
precompute_ref_log_probs=False,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
ref_adapter_name=None,
ref_model_init_kwargs=None,
ref_model_mixup_alpha=0.9,
ref_model_sync_steps=64,
reference_free=False,
remove_unused_columns=False,
report_to=['tensorboard'],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
rpo_alpha=None,
run_name=/hdd/u202320081001054/LLM-Dojo/output,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=epoch,
save_total_limit=2,
seed=42,
skip_memory_metrics=True,
split_batches=None,
sync_ref_model=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
truncation_mode=keep_end,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=10,
weight_decay=0.0,
)
2024-07-27 00:22:21.005 | INFO     | __main__:create_tokenizer:89 - vocab_size of tokenizer: 151643
2024-07-27 00:22:21.006 | INFO     | __main__:create_model:95 - Loading model from base model: Qwen/Qwen2-7B-Instruct
2024-07-27 00:22:21.006 | INFO     | __main__:create_model:96 - Train model with lora
2024-07-27 00:22:21.336 | INFO     | __main__:create_tokenizer:89 - vocab_size of tokenizer: 151643
2024-07-27 00:22:21.337 | INFO     | __main__:create_model:95 - Loading model from base model: Qwen/Qwen2-7B-Instruct
2024-07-27 00:22:21.337 | INFO     | __main__:create_model:96 - Train model with lora
Downloading shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 3793.18it/s]
Downloading shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 3667.95it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  5.74it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  8.14it/s]
2024-07-27 00:22:25.927 | INFO     | __main__:find_all_linear_names:67 - LoRA target module names: ['q_proj', 'down_proj', 'up_proj', 'gate_proj', 'k_proj', 'o_proj', 'v_proj']
2024-07-27 00:22:25.930 | INFO     | __main__:create_model:155 - Total model params: 7615.62M
2024-07-27 00:22:26.037 | INFO     | __main__:find_all_linear_names:67 - LoRA target module names: ['up_proj', 'o_proj', 'q_proj', 'down_proj', 'gate_proj', 'k_proj', 'v_proj']
Traceback (most recent call last):
  File "/hdd/u202320081001054/LLM-Dojo/main_train.py", line 251, in <module>
    main()
  File "/hdd/u202320081001054/LLM-Dojo/main_train.py", line 236, in main
    trainer = create_trainer(args, train_args)
  File "/hdd/u202320081001054/LLM-Dojo/main_train.py", line 221, in create_trainer
    trainer = DPOTrainer(
  File "/home/u202320081001054/miniconda3/envs/deepspeed-chat/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/u202320081001054/miniconda3/envs/deepspeed-chat/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py", line 515, in __init__
    self.f_divergence_type = args.f_divergence_type
AttributeError: 'TrainArgument' object has no attribute 'f_divergence_type'
Traceback (most recent call last):
  File "/hdd/u202320081001054/LLM-Dojo/main_train.py", line 251, in <module>
    main()
  File "/hdd/u202320081001054/LLM-Dojo/main_train.py", line 236, in main
    trainer = create_trainer(args, train_args)
  File "/hdd/u202320081001054/LLM-Dojo/main_train.py", line 221, in create_trainer
    trainer = DPOTrainer(
  File "/home/u202320081001054/miniconda3/envs/deepspeed-chat/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/u202320081001054/miniconda3/envs/deepspeed-chat/lib/python3.10/site-packages/trl/trainer/dpo_trainer.py", line 515, in __init__
    self.f_divergence_type = args.f_divergence_type
AttributeError: 'TrainArgument' object has no attribute 'f_divergence_type'
[2024-07-27 00:22:41,782] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 31640
[2024-07-27 00:22:41,840] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 31641
[2024-07-27 00:22:41,840] [ERROR] [launch.py:325:sigkill_handler] ['/home/u202320081001054/miniconda3/envs/deepspeed-chat/bin/python3.10', '-u', '/hdd/u202320081001054/LLM-Dojo/main_train.py', '--local_rank=1'] exits with return code = 1

**Comment by mst272** [comment]
已修复 拉取最新版本即可
